version: "3.9"

services:
  mongo:
    image: mongo:jammy
    restart: unless-stopped
    healthcheck:
      test: "mongosh --eval \"db.runCommand('ping').ok\" --quiet || exit 1"
    volumes:
      - /var/opt/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017

  express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
